
# https://github.com/catppuccin/catppuccin
flamigo = "#F2CDCD"
mauve = "#DDB6F2"
pink = "#F5C2E7"
maroon = "#E8A2AF"
red = "#F28FAD"
peach = "#F8BD96"
yellow = "#FAE3B0"
green = "#ABE9B3" 
teal = "#B5E8E0"
blue = "#96CDFB"
sky = "#89DCEB"

black0 = "#161320"
black1 = "#1A1826"
black2 = "#1E1E2E"
black3 = "#302D41"
black4 = "#575268"
gray0 = "#6E6C7E"
gray1 = "#988BA2"
gray2 = "#C3BAC6"
white = "#D9E0EE"
lavender = "#C9CBFF" 
rosewater = "#F5E0DC"

"lapce.active_tab" = "$black0"
"lapce.inactive_tab" = "$black4"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "$black1"
"lapce.border" = "$black0"
"lapce.scroll_bar" = "$grey0"

"terminal.cursor" = "$rosewater"
"terminal.foreground" = "$white"
"terminal.background" = "$black2"
"terminal.white" = "$white"
"terminal.black" = "$black0"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$sky"
"terminal.magenta" = "$mauve"
"terminal.bright_white" = "$rosewater"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$sky"
"terminal.bright_magenta" = "$mauve"
"terminal.bright_black" = "$black4"

"editor.background" = "$black2"
"editor.foreground" = "$white"
"editor.dim" = "$gray1"
"editor.focus" = "$blue"
"editor.caret" = "$rosewater"
"editor.selection" = "$black3"
"editor.current_line" = "$black1"
"editor.link" = "$rosewater"

"source_control.added" = "$black3"
"source_control.removed" = "$green"
"source_control.modified" = "$sky"

"palette.background" = "$black1"
"palette.current" = "$black2"

"completion.background" = "$black0"
"completion.current" = "$black1"

"hover.background" = "$black0"

"panel.background" = "$black2"
"panel.current" = "$black1"
"panel.hovered" = "$black3"

"status.background" = "$black1"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$maroon"

"markdown.blockquote" = "$gray0"

"style.comment" = "$gray2"

"style.constant" = "$yellow"
"style.type" = "$yellow"
"style.typeAlias" = "$yellow"
"style.number" = "$yellow"
"style.enum" = "$yellow"
"style.struct" = "$yellow"
"style.structure" = "$yellow"
"style.interface" = "$yellow"
"style.attribute" = "$yellow"
"style.constructor" = "$yellow"

"style.function" = "$blue"
"style.method" = "$blue"
"style.function.method" = "$blue"

"style.keyword" = "$maroon"
"style.selfKeyword" = "$maroon"

"style.field" = "$red"
"style.property" = "$red"
"style.enumMember" = "$red"
"style.enum-member" = "$red"
"style.variable.other.member" = "$red"

"style.string" = "$green"

"style.type.builtin" = "$sky"
"style.builtinType" = "$sky"
"style.escape" = "$sky"
"style.embedded" = "$sky"