[theme]
name = "Catppuccin"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

# https://github.com/catppuccin/catppuccin
[theme.base]

rosewater = "#f4dbd6"
flamigo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95" 
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#363a4f"
surface0 = "#414559"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"


[theme.syntax]
"comment" = "$gray2"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$maroon"
"selfKeyword" = "$maroon"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "$green"
"type.builtin" = "$sky"
"builtinType" = "$sky"
"escape" = "$sky"
"embedded" = "$sky"

[theme.ui]
"lapce.active_tab" = "$black0"
"lapce.inactive_tab" = "$black4"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "$black1"
"lapce.border" = "$black1"
"lapce.scroll_bar" = "$grey0"

"editor.background" = "$black2"
"editor.foreground" = "$white"
"editor.dim" = "$gray1"
"editor.focus" = "$blue"
"editor.caret" = "$rosewater"
"editor.selection" = "$black3"
"editor.current_line" = "$black1"
"editor.link" = "$sky"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "$black1"
"palette.current" = "$black2"

"completion.background" = "$black0"
"completion.current" = "$black1"

"hover.background" = "$black0"

"activity.background" = "$black0"
"activity.current" = "$black1"

"panel.background" = "$black2"
"panel.current" = "$black1"
"panel.hovered" = "$black3"

"status.background" = "$black1"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$maroon"

"markdown.blockquote" = "$gray0"

"terminal.cursor" = "$rosewater"
"terminal.foreground" = "$white"
"terminal.background" = "$black2"
"terminal.white" = "$white"
"terminal.black" = "$black0"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$sky"
"terminal.magenta" = "$mauve"
"terminal.bright_white" = "$rosewater"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$sky"
"terminal.bright_magenta" = "$mauve"
"terminal.bright_black" = "$black4"
