[theme]
name = "Catppuccin Macchiato"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

# https://github.com/catppuccin/catppuccin
[theme.base]
rosewater = "#f4dbd6"
flamigo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95" 
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#363a4f"
surface0 = "#414559"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"






[theme.syntax]
"comment" = "$subtext1"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$purple"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "$green"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"

[theme.ui]
"lapce.active_tab" = "$black"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "$mantle"
"lapce.border" = "$mantle"
"lapce.scroll_bar" = "$grey"


"editor.background" = "#24273a"
"editor.foreground" = "$rosewater"
"editor.dim" = "$subtext1"
"editor.focus" = "#CCCCCC"
"editor.caret" = "$teal"
"editor.selection" = "$grey"
"editor.current_line" = "#2C313C"
"editor.link" = "$cyan"

"source_control.added" = "##a6d18932"
"source_control.removed" = "#ea999c32"
"source_control.modified" = "#8caaee32"

"palette.background" = "#24273a"
"palette.current" = "$surface0"

"completion.background" = "#24273a"
"completion.current" = "$surface0"

"hover.background" = "#24273a"

"activity.background" = "#24273a"
"activity.current" = "$black"

"panel.background" = "#24273a"
"panel.current" = "$surface0"
"panel.hovered" = "#343A45"

"status.background" = "#24273a"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "$subtext0"

"terminal.cursor" = "$rosewater"
"terminal.foreground" = "$rosewater"
"terminal.background" = "#24273a"
"terminal.white" = "$rosewater"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$rosewater"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$crust"
