#:schema https://raw.githubusercontent.com/ghishadow/lapce-schema/blob/main/theme.schema.json
[color-theme]
name = "Catppuccin Mocha"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

# for color reference
# rosewater = "#f5e0dc"
# flamigo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# maroon = "#eba0ac"
# peach = "#fab387"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"

[color-theme.base]

black = "#45475A" # surface1
blue = "#89b4fa" # blue
cyan = "#94E2D5" # teal
green = "#A6E3A1" # green
magenta = "#F5C2E7" # pink
orange = "#fab387" # peach
purple = "#cba6f7"  # mauve
red = "#F38BA8" # red
white = "#BAC2DE" # subtext1
yellow = "#F9E2AF" # yellow

[color-theme.syntax]
"comment" = "#7f849c"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"

"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"

"keyword" = "#cba6f7"
"selfKeyword" = "#cba6f7"

"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"

"string" = "$green"
"string.escape" = "$cyan"

"type.builtin" = "#94e2d5"       #teal
"builtinType" = "#94e2d5"        #teal
"escape" = "#94e2d5"             #teal
"embedded" = "#94e2d5"           #teal

"punctuation.delimiter" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
"text.reference" = "$yellow"
"variable" = "$red"
"variable.other.member" = "$green"
"tag" = "$blue"


[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#181825"
"lapce.border" = "#181825"
"lapce.scroll_bar" = "#6c7086"

"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$black"

# tab
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#528BFF"

"lapce.tab.inactive.background" = "#21252b"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#528BFF77"

"lapce.tab.separator" = ""

"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"

"lapce.remote.local" = "#4078F2"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$white"
"lapce.plugin.author" = "#B0B0B0"


"editor.background" = "#1e1e2e"
"editor.foreground" = "#bac2de"
"editor.dim" = "#7f849c"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#94e2d5"
"editor.selection" = "#585b70"
"editor.current_line" = "#2C313C"
"editor.link" = "#f5e0dc"

"inlay_hint.foreground" = "#7f849c"
"inlay_hint.background" = "#585b7050"

"source_control.added" = "##a6d18932"
"source_control.removed" = "#ea999c32"
"source_control.modified" = "#8caaee32"

"palette.background" = "#1e1e2e"
"palette.current" = "#585b70"

"completion.background" = "#1e1e2e"
"completion.current" = "#585b70"

"hover.background" = "#1e1e2e"

"activity.background" = "#1e1e2e"
"activity.current" = "#585b70"

"panel.background" = "#1e1e2e"
"panel.foreground" = "$black"
"panel.foreground.dim" = "#A0A1A7"
"panel.current.background" = "#DBDBDC"
"panel.current.foreground" = "$black"
"panel.current.foreground.dim" = "#A0A1A7"
"panel.hovered.background" = "#E4E4E6"
"panel.hovered.foreground" = "$black"
"panel.hovered.foreground.dim" = "#A0A1A7"

"status.background" = "#1e1e2e"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "#cba6f7"

"markdown.blockquote" = "#a6adc8"

"terminal.cursor" = "#f5e0dc"
"terminal.foreground" = "#cdd6f4"
"terminal.background" = "#1e1e2e"
"terminal.white" = "#bac2de"
"terminal.black" = "#45475a"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "#94e2d5"           #teal
"terminal.magenta" = "#f5c2e7"
"terminal.bright_white" = "#a6adc8"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "#94e2d5"    #teal
"terminal.bright_magenta" = "#f5c2e7" #pink
"terminal.bright_black" = "#585b70"   #surface2
