[theme]
name = "Catppuccin Frappe"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

# https://github.com/catppuccin/catppuccin
[theme.base]
rosewater = "#f2d5cf"
flamigo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189" 
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"



[theme.syntax]
"comment" = "$subtext1"
"constant" = "#e5c890"
"type" = "#e5c890"
"typeAlias" = "#e5c890"
"number" = "#e5c890"
"enum" = "#e5c890"
"struct" = "#e5c890"
"structure" = "#e5c890"
"interface" = "#e5c890"
"attribute" = "#e5c890"
"constructor" = "#e5c890"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$purple"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "#a6d189"
"type.builtin" = "#81c8be"
"builtinType" = "#81c8be"
"escape" = "#81c8be"
"embedded" = "#81c8be"

[theme.ui]
"lapce.active_tab" = "#51576d"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "#e5c890"
"lapce.dropdown_shadow" = "$mantle"
"lapce.border" = "$mantle"
"lapce.scroll_bar" = "$grey"


"editor.background" = "#303446"
"editor.foreground" = "#b5bfe2"
"editor.dim" = "$subtext1"
"editor.focus" = "#CCCCCC"
"editor.caret" = "$teal"
"editor.selection" = "$grey"
"editor.current_line" = "#2C313C"
"editor.link" = "#81c8be"

"source_control.added" = "##a6d18932"
"source_control.removed" = "#ea999c32"
"source_control.modified" = "#8caaee32"

"palette.background" = "#303446"
"palette.current" = "$surface0"

"completion.background" = "#303446"
"completion.current" = "$surface0"

"hover.background" = "#303446"

"activity.background" = "#303446"
"activity.current" = "#51576d"

"panel.background" = "#303446"
"panel.current" = "$surface0"
"panel.hovered" = "#343A45"

"status.background" = "#303446"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "#e5c890"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#a5adce"

"terminal.cursor" = "#b5bfe2"
"terminal.foreground" = "#c6d0f5"
"terminal.background" = "#303446"
"terminal.white" = "#b5bfe2"
"terminal.black" = "#51576d"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "#a6d189"
"terminal.yellow" = "#e5c890"
"terminal.cyan" = "#81c8be"
"terminal.magenta" = "#f4b8e4"
"terminal.bright_white" = "#b5bfe2"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "#a6d189"
"terminal.bright_yellow" = "#e5c890"
"terminal.bright_cyan" = "#81c8be"
"terminal.bright_magenta" = "#f4b8e4"
"terminal.bright_black" = "#626880"