[theme]
name = "Catppuccin Macchiato"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

# https://github.com/catppuccin/catppuccin
[theme.base]
rosewater = "#f4dbd6"
flamigo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95" 
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#363a4f"
surface0 = "#414559"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"






[theme.syntax]
"comment" = "#8087a2"
"constant" = "#eed49f"
"type" = "#eed49f"
"typeAlias" = "#eed49f"
"number" = "#eed49f"
"enum" = "#eed49f"
"struct" = "#eed49f"
"structure" = "#eed49f"
"interface" = "#eed49f"
"attribute" = "#eed49f"
"constructor" = "#eed49f"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "#c6a0f6"
"selfKeyword" = "#c6a0f6"
"field" = "#ed8796"
"property" = "#ed8796"
"enumMember" = "#ed8796"
"enum-member" = "#ed8796"
"variable.other.member" = "#ed8796"
"string" = "$green"
"type.builtin" = "#bbd5ca"
"builtinType" = "#bbd5ca"
"escape" = "#bbd5ca"
"embedded" = "#bbd5ca"

[theme.ui]
"lapce.active_tab" = "#5b6078"
"lapce.inactive_tab" = "#6e738d"
"lapce.error" = "#ed8796"
"lapce.warn" = "#eed49f"
"lapce.dropdown_shadow" = "#1e2030"
"lapce.border" = "#1e2030"
"lapce.scroll_bar" = "#6e738d"


"editor.background" = "#24273a"
"editor.foreground" = "#f4dbd6"
"editor.dim" = "#b7bdf8"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#8bd5ca"
"editor.selection" = "#5b6078"
"editor.current_line" = "#2C313C"
"editor.link" = "#f4dbd6"

"inlay_hint.foreground" = "#8087a2"
"inlay_hint.background" = "#5b607850"

"source_control.added" = "##a6d18932"
"source_control.removed" = "#ea999c32"
"source_control.modified" = "#8caaee32"

"palette.background" = "#24273a"
"palette.current" = "#5b6078"

"completion.background" = "#24273a"
"completion.current" = "#5b6078"

"hover.background" = "#24273a"

"activity.background" = "#24273a"
"activity.current" = "#5b6078"

"panel.background" = "#24273a"
"panel.current" = "#5b6078"
"panel.hovered" = "#343A45"

"status.background" = "#24273a"
"status.modal.normal" = "$blue"
"status.modal.insert" = "#ed8796"
"status.modal.visual" = "#eed49f"
"status.modal.terminal" = "#c6a0f6"

"markdown.blockquote" = "#a5adcb"

"terminal.cursor" = "#f4dbd6"
"terminal.foreground" = "#cad3f5"
"terminal.background" = "#24273a"
"terminal.white" = "#a5adcb"
"terminal.black" = "#494d64"
"terminal.red" = "#ed8796"
"terminal.blue" = "#8aadf4"
"terminal.green" = "#ebff87"
"terminal.yellow" = "#eed49f"
"terminal.cyan" = "#bbd5ca"
"terminal.magenta" = "#c6a0f6"
"terminal.bright_white" = "#bbc0e0"
"terminal.bright_red" = "#ed8796"
"terminal.bright_blue" = "#8aadf4"
"terminal.bright_green" = "#rbff87"
"terminal.bright_yellow" = "#eed49f"
"terminal.bright_cyan" = "#bbd5ca"
"terminal.bright_magenta" = "#c6a0f6"
"terminal.bright_black" = "#586078"

