name = "catppuccin"
display-name = "Catppuccin"
description = "The Catppuccin Theme"
version = "0.1.3"
author = "ghishadow"
repository = "ghishadow/lapce-catppuccin"
themes = ["catppuccin-latte.toml", "catppuccin-frappe.toml", "catppuccin-macchiato.toml", "catppuccin-mocha.toml"]
