name = "catppuccin"
display-name = "Catppuccin"
description = "🐭 Soothing pastel theme for Lapce"
version = "0.1.8"
author = "ghishadow"
repository = "ghishadow/lapce-catppuccin"
themes = ["catppuccin-latte.toml", "catppuccin-frappe.toml", "catppuccin-macchiato.toml", "catppuccin-mocha.toml"]
